all:
	gcc -o Print_array Print_array.c
	gcc -o Print_reverse_array Print_reverse_array.c
	gcc -o Fill_upper_array_triangle Fill_upper_array_triangle.c
	gcc -o Array_spiral_filling Array_spiral_filling.c

clean:
	rm -f Print_array
	rm -f Print_reverse_array
	rm -f Fill_upper_array_triangle
	rm -f Array_spiral_filling
